# Generated by Django 4.2.4 on 2024-11-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
