# Generated by Django 4.2.4 on 2024-11-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_publicacion_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='descripcion_oficio',
            field=models.CharField(blank=True, help_text="Describa el oficio si 'Otro' fue seleccionado", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='oficio',
            field=models.CharField(choices=[('fontaneria', 'Técnico en fontanería'), ('electricidad', 'Técnico en electricidad'), ('climatizacion', 'Técnico en climatización'), ('carpinteria', 'Técnico en carpintería'), ('pintura', 'Técnico en pintura'), ('cerrajeria', 'Técnico en cerrajería'), ('electrodomesticos', 'Técnico en reparación de electrodomésticos'), ('seguridad', 'Técnico en instalación de sistemas de seguridad'), ('jardineria', 'Técnico en mantenimiento de jardines'), ('gas', 'Técnico en gas'), ('energias_renovables', 'Técnico en instalación de sistemas de energía renovable'), ('domotica', 'Técnico en sistemas de domótica'), ('dranaje', 'Técnico en drenaje y saneamiento'), ('impermeabilizacion', 'Técnico en impermeabilización'), ('piscinas', 'Técnico en mantenimiento de piscinas'), ('remodelacion', 'Técnico en remodelación de interiores'), ('otros', 'Otro')], default='otros', max_length=50),
        ),
    ]
