# Generated by Django 4.2.4 on 2024-11-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_publicacion_descripcion_oficio_publicacion_oficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='descripcion_oficio',
        ),
    ]
