# Generated by Django 4.2.4 on 2024-11-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
